<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	<LangVersion>9.0</LangVersion>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="cp $(ProjectDir)bin/Debug/netstandard2.1/Hytone.Timberborn.Plugins.Floodgates.dll /home/hannuh/.steam/steam/steamapps/compatdata/1062090/pfx/drive_c/users/steamuser/Documents/Timberborn/Mods/SimpleFloodgateTriggers/version-0.7" />
  </Target>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.3.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="package\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Managed\Timberborn*.dll" />
    <Reference Include="Managed\UnityEngine*.dll" />
    <Reference Include="Managed\Bindito*.dll" />
    <Reference Include="TimberAPI\version-0.7\core\*.dll" />
  </ItemGroup>

</Project>
